### ISSUE TITLE
Add UART-Programmer reset logic to HW

### ISSUE THREAD

**Issue by LIFsCode** [LIFsCode/ELOC-3.0#28]
Currently the EN, GPIO0, GPIO2 Pins have to be set manually if the ESP should be programmed via UART.

This can be avoided by a few transisotrs on the board:
<img width="410" alt="Screen Shot 2017-05-27 at 10 59 07" src="https://github.com/LIFsCode/ELOC-3.0/assets/109753539/b8296e2f-1f03-40b5-b489-539168768409">

Source from here: https://esp32.com/viewtopic.php?t=1914

Requires 2 additional UART signals (DTR, RTS) on a pin header.

**Comment by EDsteve** [comment]
@LIFsCode 
Thanks. I was never really sure how it would work. Now i know :)
But my USB-TTL converter does not have a RTS or DTR pin and the USB-TTL adapter you have has a no DTR pin. So we would need a different USB-TTL adapter i guess?

P.S.: Finally back home and do some timedrift and power tests now.

**Comment by LIFsCode** [comment]
You could leave the buttons as is, so you always have a backup plan ^^

Anyway I think the USB TLT adapter has DTR, but simple not routed to the pin header
![grafik](https://github.com/LIFsCode/ELOC-3.0/assets/109753539/f34868a5-c749-4d7a-8745-efe315eceb31)

So maybe we just have to add another pin header and modify the housing
