### ISSUE TITLE
Adding voltage and temperature readings to log during record

### ISSUE THREAD

**Issue by EDsteve** [LIFsCode/ELOC-3.0#38]
Small job :)
It logs voltage and temp in stand by. But it would be helpful if we can also log the voltages and temperatures during recording.

For now it only writes this during recording:
I (720719) main: record in second loop--voltage check

Possible?

Cheers 
ED

**Comment by OOHehir** [comment]
I should be able to incorporate this in the 'main' loop. How often should
it be recorded while inference or recording is occurring?

**Comment by EDsteve** [comment]
@OOHehir It should write it during every status to the log besides in sleep mode. Not sure if you have seen the changes in the master branch. @LIFsCode added the option to store the logs on the SD card. Temperature and voltages are interesting for us every 10 or 30 minutes. But more often doesn't hurt much :)

So we can get an idea how well the solar panel is charging (For example if something grows over the panel or if the batteries are getting old/bad).

**Comment by LIFsCode** [comment]
I the long run I plan to add a status task for handling all this small stuff ( battery, temperature, click detection, later GPS, buzzer, led, etc) in a centralized way.

**Comment by LIFsCode** [comment]
this should be done with [this commit](https://github.com/LIFsCode/ELOC-3.0/commit/cf51c0378c7afd5d93d96bc6fc62fe502a3b9fc0)
